NumPy Retail Analytics Assignment
Business Scenario
You are working as a Data Analyst for SmartMart Retail Stores. The company operates five stores in different cities and sells six major product categories.

Management wants to analyze sales performance, expenses, profits, targets, discounts, inventory, and store-level performance using NumPy.

You are provided with two main NumPy arrays:

sales_data — monthly sales revenue generated by each store for different product categories.
cost_data — total cost incurred by each store for the same product categories.

In [132]:
import numpy as np

# Store names
stores = np.array([
    "Bengaluru",
    "Hyderabad",
    "Chennai",
    "Mumbai",
    "Pune"
])

# Product categories
categories = np.array([
    "Electronics",
    "Groceries",
    "Clothing",
    "Furniture",
    "Beauty",
    "Sports"
])

# Sales revenue in rupees
# Rows represent stores
# Columns represent product categories

sales_data = np.array([
    [850000, 420000, 310000, 275000, 190000, 225000],
    [780000, 460000, 295000, 310000, 210000, 240000],
    [920000, 390000, 340000, 260000, 185000, 215000],
    [1050000, 510000, 375000, 345000, 250000, 290000],
    [690000, 405000, 280000, 225000, 175000, 205000]
])

# Cost incurred in rupees
# Rows represent stores
# Columns represent product categories

cost_data = np.array([
    [640000, 315000, 220000, 205000, 125000, 160000],
    [590000, 350000, 210000, 225000, 140000, 170000],
    [700000, 295000, 245000, 195000, 120000, 155000],
    [790000, 390000, 265000, 250000, 165000, 205000],
    [530000, 310000, 205000, 170000, 115000, 145000]
])

print("Stores:")
print(stores)

print("\nProduct Categories:")
print(categories)

print("\nSales Data:")
print(sales_data)

print("\nCost Data:")
print(cost_data)

Stores:
['Bengaluru' 'Hyderabad' 'Chennai' 'Mumbai' 'Pune']

Product Categories:
['Electronics' 'Groceries' 'Clothing' 'Furniture' 'Beauty' 'Sports']

Sales Data:
[[ 850000  420000  310000  275000  190000  225000]
 [ 780000  460000  295000  310000  210000  240000]
 [ 920000  390000  340000  260000  185000  215000]
 [1050000  510000  375000  345000  250000  290000]
 [ 690000  405000  280000  225000  175000  205000]]

Cost Data:
[[640000 315000 220000 205000 125000 160000]
 [590000 350000 210000 225000 140000 170000]
 [700000 295000 245000 195000 120000 155000]
 [790000 390000 265000 250000 165000 205000]
 [530000 310000 205000 170000 115000 145000]]


Part 2: Basic Array Understanding
Question 1: Array Dimensions
The finance manager wants to confirm how many stores and product categories are present in the data.

Write NumPy code to display:

Number of dimensions in sales_data
Shape of sales_data
Total number of values
Data type of the array
Memory occupied by the array

In [133]:
# Number of dimensions in sales_data

sales_data.ndim

2

In [134]:
# Shape of sales_data

sales_data.shape

(5, 6)

In [135]:
# Total number of values
sales_data.size

30

In [136]:
# Data type of the array
sales_data.dtype

dtype('int64')

In [137]:
# Memory occupied by the array
sales_data.nbytes

240

Question 2: Store and Category Count
Calculate the following:

Total number of stores
Total number of product categories
Total number of store-category combinations

In [138]:
# Total number of stores
stores.size

5

In [139]:
# Total number of product categories
categories.size

6

In [140]:
# Total number of store-category combinations
total_combinations=len(stores)*len(categories)
print(total_combinations)

30


Question 3: Sales Data Type Conversion
The reporting application requires sales values in floating-point format.

Convert sales_data into:

float32
float64
Compare the memory used by both arrays.

In [141]:
# float32
print(sales_data.astype(np.float32))

# float64
print('folat 64')
print(sales_data.astype(np.float64))

[[ 850000.  420000.  310000.  275000.  190000.  225000.]
 [ 780000.  460000.  295000.  310000.  210000.  240000.]
 [ 920000.  390000.  340000.  260000.  185000.  215000.]
 [1050000.  510000.  375000.  345000.  250000.  290000.]
 [ 690000.  405000.  280000.  225000.  175000.  205000.]]
folat 64
[[ 850000.  420000.  310000.  275000.  190000.  225000.]
 [ 780000.  460000.  295000.  310000.  210000.  240000.]
 [ 920000.  390000.  340000.  260000.  185000.  215000.]
 [1050000.  510000.  375000.  345000.  250000.  290000.]
 [ 690000.  405000.  280000.  225000.  175000.  205000.]]


Part 3: Indexing and Data Extraction
Question 4: Bengaluru Store Analysis
The Bengaluru regional manager wants to review sales for all product categories.

Extract and display the complete sales row for Bengaluru.

In [142]:
bengaluru_sales=sales_data[0]
print("bengaluru_sales")
print(bengaluru_sales)
for category,sales in zip(categories,bengaluru_sales):
    print(category,sales)

bengaluru_sales
[850000 420000 310000 275000 190000 225000]
Electronics 850000
Groceries 420000
Clothing 310000
Furniture 275000
Beauty 190000
Sports 225000


Question 5: Mumbai Cost Analysis
Extract the total cost incurred by the Mumbai store for all product categories.

In [143]:
Mumbai_index=np.where(stores=='Mumbai')[0][0]
print(Mumbai_index)
total_cost=cost_data[Mumbai_index]
print(total_cost)
print(sum(total_cost))

3
[790000 390000 265000 250000 165000 205000]
2065000


Question 6: Electronics Sales Across Stores
The electronics department wants to compare its sales performance across all five stores.

Extract the Electronics sales column from sales_data.

In [144]:
import numpy as np
electronic_index=np.where(categories=='Electronics')[0][0]
electronics=sales_data[:,electronic_index]
for store,electronic in zip(stores,electronics):
    print(store,electronic)

Bengaluru 850000
Hyderabad 780000
Chennai 920000
Mumbai 1050000
Pune 690000


Question 7: Clothing Cost Across Stores
Extract the Clothing cost for every store from cost_data.

In [145]:
clothing_index=np.where(categories=='Clothing')[0][0]
clothing_costs=cost_data[:,clothing_index]
for store,clothing_cost in zip(stores,clothing_costs):
    print(store,clothing_cost)

Bengaluru 220000
Hyderabad 210000
Chennai 245000
Mumbai 265000
Pune 205000


Question 8: Hyderabad Furniture Performance
Find the following for Hyderabad:

Furniture sales
Furniture cost
Furniture profit

In [146]:
import numpy as np
hyderabad_index=np.where(stores=='Hyderabad')[0][0]
furniture_index=np.where(categories=='Furniture')[0][0]
furniture_sales=sales_data[hyderabad_index][furniture_index]
furniture_cost=cost_data[hyderabad_index][furniture_index]
furniture_profit=furniture_sales-furniture_cost
print(furniture_sales)
print(furniture_cost)
print(furniture_profit)

310000
225000
85000


Question 9: Chennai Category Range
Extract Chennai’s sales for the following categories:

Groceries
Clothing
Furniture
Use array slicing.

In [147]:
chennai_index=np.where(stores=='Chennai')[0][0]
sales=np.where(np.isin(categories,['Groceries','Clothing','Furniture']))[0]
sales_d=sales_data[chennai_index,sales]
print(sales_d)

[390000 340000 260000]


Question 10: Selected Store Analysis
Extract sales data for:

Bengaluru
Chennai
Pune
Include only:

Electronics
Clothing
Beauty
Use advanced indexing.

In [148]:
store_indices = np.where(
    np.isin(stores, ["Bengaluru", "Chennai", "Pune"]))[0]
category_indices = np.where(
    np.isin(categories, ["Electronics", "Clothing", "Beauty"]))[0]
selected_sales = sales_data[np.ix_(store_indices, category_indices)]

print(selected_sales)



[[850000 310000 190000]
 [920000 340000 185000]
 [690000 280000 175000]]


Part 4: Sales Aggregation
Question 11: Company-Wide Sales
Calculate the total sales revenue generated by all stores and all categories.

In [149]:
totalsales=np.sum(sales_data)
print(totalsales)

11675000


Question 12: Store-Wise Sales
Calculate total sales revenue for each store.

Display the result together with the store names.

Expected output format:

Bengaluru: total sales
Hyderabad: total sales
Chennai: total sales
Mumbai: total sales
Pune: total sales

In [150]:
totalsales=np.sum(sales_data,axis=1)
for store,totalsale in zip(stores,totalsales):
    print(store ,':', totalsale)

Bengaluru : 2270000
Hyderabad : 2295000
Chennai : 2310000
Mumbai : 2820000
Pune : 1980000


Question 13: Category-Wise Sales
Calculate total sales for each product category across all stores.

Display each category name with its total sales.

In [151]:
totalsales=np.sum(sales_data,axis=0)
for category,totalsale in zip(categories,totalsales):
    print(category ,':', totalsale)

Electronics : 4290000
Groceries : 2185000
Clothing : 1600000
Furniture : 1415000
Beauty : 1010000
Sports : 1175000


Question 14: Average Sales Per Store
Calculate the average sales generated by each store across all six product categories.

In [152]:
totalsales=np.mean(sales_data,axis=1)
for sales,avg in zip(categories,totalsales):
    print(f'{sales} : {avg:.2f}')

Electronics : 378333.33
Groceries : 382500.00
Clothing : 385000.00
Furniture : 470000.00
Beauty : 330000.00


Question 15: Average Sales Per Category
Calculate the average sales of each product category across the five stores.

In [153]:
totalsales=np.mean(sales_data,axis=0)
for category,avg in zip(categories,totalsales):
    print(f'{category} : {avg:.2f}')

Electronics : 858000.00
Groceries : 437000.00
Clothing : 320000.00
Furniture : 283000.00
Beauty : 202000.00
Sports : 235000.00


Question 16: Highest-Selling Store
Identify:

Index of the store with the highest total sales
Name of the store
Total sales generated by that store
Use np.argmax().

In [154]:
store_sales=np.sum(sales_data,axis=1)
print(store_sales)
highest_index=np.argmax(store_sales)
print(f'highest_index : {highest_index}')
print(f'highest Store name : {stores[highest_index]}')
print(f'Total Sales : {store_sales[highest_index]}')

[2270000 2295000 2310000 2820000 1980000]
highest_index : 3
highest Store name : Mumbai
Total Sales : 2820000


Question 17: Lowest-Selling Store
Identify the store with the lowest overall sales.

Use np.argmin().

In [155]:
store_sales=np.sum(sales_data,axis=1)
print(store_sales)
lowest_index=np.argmin(store_sales)
print(f'lowest_index : {lowest_index}')
print(f'lowest Store name : {stores[lowest_index]}')
print(f'Total Sales : {store_sales[lowest_index]}')

[2270000 2295000 2310000 2820000 1980000]
lowest_index : 4
lowest Store name : Pune
Total Sales : 1980000


Question 18: Highest-Selling Category
Find the product category that generated the highest total sales across the company.

In [156]:
category_sales=np.sum(sales_data,axis=0)
print(category_sales)
highest_index=np.argmax(category_sales)
print(f'highest_index : {highest_index}')
print(f'highest Store name : {categories[highest_index]}')
print(f'Total Sales : {category_sales[highest_index]}')

[4290000 2185000 1600000 1415000 1010000 1175000]
highest_index : 0
highest Store name : Electronics
Total Sales : 4290000


Question 19: Lowest-Selling Category
Find the product category with the lowest total sales across all stores

In [157]:
category_sales=np.sum(sales_data,axis=0)
print(category_sales)
lowest_index=np.argmin(category_sales)
print(f'lowest_index : {lowest_index}')
print(f'lowest category name : {categories[lowest_index]}')
print(f'Total Sales : {category_sales[lowest_index]}')

[4290000 2185000 1600000 1415000 1010000 1175000]
lowest_index : 4
lowest category name : Beauty
Total Sales : 1010000


Part 5: Cost Analysis
Question 20: Total Company Cost
Calculate the total cost incurred by SmartMart across all stores and product categories.

In [158]:
total_cost=np.sum(cost_data)
print(total_cost)

8600000


Question 21: Store-Wise Cost
Calculate the total cost incurred by each store

In [159]:
total_cost=np.sum(cost_data,axis=1)
print(total_cost)
for store,totalcost in zip(stores,total_cost):
    print(store ,':', totalcost)

[1665000 1685000 1710000 2065000 1475000]
Bengaluru : 1665000
Hyderabad : 1685000
Chennai : 1710000
Mumbai : 2065000
Pune : 1475000


Question 22: Category-Wise Cost
Calculate the total cost incurred for each product category across all stores.

In [160]:
total_cost=np.sum(cost_data,axis=0)
print(total_cost)
for category,totalcost in zip(categories,total_cost):
    print(category ,':', totalcost)

[3250000 1660000 1145000 1045000  665000  835000]
Electronics : 3250000
Groceries : 1660000
Clothing : 1145000
Furniture : 1045000
Beauty : 665000
Sports : 835000


Question 23: Most Expensive Store
Identify the store with the highest total operating cost.

In [161]:
store_cost=np.sum(cost_data,axis=1)
print(store_cost)
highest_index=np.argmax(store_cost)
print(f'highest_index : {highest_index}')
print(f'highest Store name : {stores[highest_index]}')
print(f'Total cost : {store_cost[highest_index]}')

[1665000 1685000 1710000 2065000 1475000]
highest_index : 3
highest Store name : Mumbai
Total cost : 2065000


Question 24: Lowest-Cost Store
Identify the store with the lowest total cost.

In [162]:
store_cost=np.sum(cost_data,axis=1)
print(store_cost)
lowest_index=np.argmin(store_cost)
print(f'lowest_index : {lowest_index}')
print(f'lowest Store name : {stores[lowest_index]}')
print(f'Total cost : {store_cost[lowest_index]}')

[1665000 1685000 1710000 2065000 1475000]
lowest_index : 4
lowest Store name : Pune
Total cost : 1475000


Question 25: Most Expensive Product Category
Determine which product category has the highest total cost across all stores.

In [163]:
category_cost=np.sum(cost_data,axis=0)
print(category_cost)
highest_index=np.argmax(category_cost)
print(f'highest_index : {highest_index}')
print(f'highest category name : {categories[highest_index]}')
print(f'Total cost : {category_cost[highest_index]}')

[3250000 1660000 1145000 1045000  665000  835000]
highest_index : 0
highest category name : Electronics
Total cost : 3250000


Part 6: Profit Analysis Using Two Arrays
Question 26: Profit Matrix
Calculate the profit generated for every store and product category.

Use:

profit_data = sales_data - cost_data
Display the complete profit matrix.

In [164]:
profit_data = sales_data - cost_data
print(profit_data)

# import pandas as pd

# profit_df = pd.DataFrame(
#     profit_data,
#     index=stores,
#     columns=categories
# )

# print(profit_df)


[[210000 105000  90000  70000  65000  65000]
 [190000 110000  85000  85000  70000  70000]
 [220000  95000  95000  65000  65000  60000]
 [260000 120000 110000  95000  85000  85000]
 [160000  95000  75000  55000  60000  60000]]



Question 27: Store-Wise Profit
Calculate the total profit generated by each store.

In [165]:
store_profit= np.sum(profit_data,axis=1)
print(store_profit)
for store, profit in zip(stores, store_profit):
    print(f"{store}: {profit}")

[605000 610000 600000 755000 505000]
Bengaluru: 605000
Hyderabad: 610000
Chennai: 600000
Mumbai: 755000
Pune: 505000


Question 28: Category-Wise Profit
Calculate the total profit generated by each product category.

In [166]:
category_profit= np.sum(profit_data,axis=0)
print(category_profit)
for category, profit in zip(categories, category_profit):
    print(f"{category}: {profit}")

[1040000  525000  455000  370000  345000  340000]
Electronics: 1040000
Groceries: 525000
Clothing: 455000
Furniture: 370000
Beauty: 345000
Sports: 340000


Question 29: Most Profitable Store
Identify the store that generated the highest total profit.

Display:

Store name
Total sales
Total cost
Total profit

In [167]:
import numpy as np
profitable_store=np.argmax(store_profit)
print(profitable_store)
print(f'store name : {stores[profitable_store]}')
print(f'total sales : {np.sum(sales_data[profitable_store])}')
print(f'tottal cost : {np.sum(cost_data[profitable_store])}')
print(f'tottal profit : {np.sum(store_profit[profitable_store])}')

3
store name : Mumbai
total sales : 2820000
tottal cost : 2065000
tottal profit : 755000


Question 30: Least Profitable Store
Identify the store that generated the lowest total profit.

In [168]:
store_sales=np.sum(sales_data,axis=1)
print(store_sales)
store_profitt=np.sum(cost_data,axis=1)
print(store_profitt)
minprofit_index=np.argmin(store_sales-store_profitt)
print(f' store that generated lowest profit : {stores[minprofit_index]}')

[2270000 2295000 2310000 2820000 1980000]
[1665000 1685000 1710000 2065000 1475000]
 store that generated lowest profit : Pune


Question 31: Most Profitable Category
Find the category with the highest total profit across all stores.

In [169]:
category_sales=np.sum(sales_data,axis=0)
print(category_sales)
category_profitt=np.sum(cost_data,axis=0)
print(category_profitt)
print(category_sales-category_profitt)
maxprofit_index=np.argmax(category_sales-category_profitt)
print(f'total profit : {category_sales[maxprofit_index]-category_profitt[maxprofit_index]}')
print(f'category that generated highest profit : {categories[maxprofit_index]}')

[4290000 2185000 1600000 1415000 1010000 1175000]
[3250000 1660000 1145000 1045000  665000  835000]
[1040000  525000  455000  370000  345000  340000]
total profit : 1040000
category that generated highest profit : Electronics


Question 32: Least Profitable Category
Find the category with the lowest total profit.

In [170]:
category_sales=np.sum(sales_data,axis=0)
print(category_sales)
category_profitt=np.sum(cost_data,axis=0)
print(category_profitt)
print(category_sales-category_profitt)
minprofit_index=np.argmin(category_sales-category_profitt)
print(f'total profit : {category_sales[minprofit_index]-category_profitt[minprofit_index]}')
print(f'category that generated lowest profit : {categories[minprofit_index]}')

[4290000 2185000 1600000 1415000 1010000 1175000]
[3250000 1660000 1145000 1045000  665000  835000]
[1040000  525000  455000  370000  345000  340000]
total profit : 340000
category that generated lowest profit : Sports


Question 33: Maximum Individual Profit
Find the highest profit generated by any single store-category combination.

Display:

Profit amount
Store name
Product category
Use np.unravel_index().

In [171]:
profit_data=sales_data-cost_data
max_index=np.unravel_index(np.argmax(profit_data),profit_data.shape)
store_index=max_index[0]
category_index=max_index[1]
print("Highest Profit:", profit_data[max_index])
print("Store:", stores[store_index])
print("Category:", categories[category_index])


Highest Profit: 260000
Store: Mumbai
Category: Electronics


Question 34: Minimum Individual Profit
Find the smallest profit generated by a store-category combination.

Display the corresponding store and category.

In [172]:
profit_data=sales_data-cost_data
min_index=np.unravel_index(np.argmin(profit_data),profit_data.shape)
store_index=min_index[0]
category_index=max_index[1]
print("lowest Profit:", profit_data[min_index])
print("Store:", stores[store_index])
print("Category:", categories[category_index])


lowest Profit: 55000
Store: Pune
Category: Electronics


Part 7: Profit Margin Analysis
Question 35: Profit Margin Matrix
Calculate the profit margin percentage for every store-category combination.

Use:

profit_margin = (profit_data / sales_data) * 100
Round the result to two decimal places.

In [173]:
profit_margin=(profit_data/sales_data)*100
print(f' {np.round(profit_margin,2)}')

 [[24.71 25.   29.03 25.45 34.21 28.89]
 [24.36 23.91 28.81 27.42 33.33 29.17]
 [23.91 24.36 27.94 25.   35.14 27.91]
 [24.76 23.53 29.33 27.54 34.   29.31]
 [23.19 23.46 26.79 24.44 34.29 29.27]]


Question 36: Store-Wise Profit Margin
Calculate the overall profit margin percentage for each store using:

In [174]:
total_profit =np.sum(profit_data,axis=1)
total_sales =np.sum(sales_data,axis=1)
store_profit_margin = (total_profit / total_sales  ) * 100
store_profit_margin = np.round(store_profit_margin, 2)
print(store_profit_margin)
for store,margin in zip(stores,store_profit_margin):
    print(store , margin)


[26.65 26.58 25.97 26.77 25.51]
Bengaluru 26.65
Hyderabad 26.58
Chennai 25.97
Mumbai 26.77
Pune 25.51



Question 37: Category-Wise Profit Margin
Calculate the overall profit margin percentage for each product category.

In [175]:
total_profit =np.sum(profit_data,axis=0)
total_sales =np.sum(sales_data,axis=0)
category_profit_margin = (total_profit / total_sales  ) * 100
category_profit_margin = np.round(category_profit_margin, 2)
print(store_profit_margin)
for store,margin in zip(categories,category_profit_margin):
    print(store , margin)


[26.65 26.58 25.97 26.77 25.51]
Electronics 24.24
Groceries 24.03
Clothing 28.44
Furniture 26.15
Beauty 34.16
Sports 28.94


Question 38: Best Store by Profit Margin
Identify the store with the highest overall profit margin.

In [176]:
best_store_index=np.argmax(store_profit_margin)
print(f'best store : {stores[best_store_index]}')
print(f'Profit Margin:{store_profit_margin[best_store_index]}%')

best store : Mumbai
Profit Margin:26.77%


Question 39: Best Category by Profit Margin
Identify the product category with the highest profit margin.

In [177]:
best_category_index=np.argmax(category_profit_margin)
print(f'best store : {categories[best_category_index]}')
print(f'Profit Margin:{category_profit_margin[best_category_index]}%')

best store : Beauty
Profit Margin:34.16%


Question 40: Low-Margin Transactions
Management considers a profit margin below 22% to be weak.

Find all store-category combinations where the profit margin is below 22%.

Display:

Store
Category
Sales
Cost
Profit
Profit margin
Use Boolean indexing.

In [178]:
low_margin=profit_margin<22
print(low_margin)
rows,cols=np.where(low_margin)
print(rows,cols)
if len(rows) == 0:
    print("No store-category combinations have profit margin below 22%.")
else:
    for r, c in zip(rows, cols):
        print("Store:", stores[r])
        print("Category:", categories[c])
        print("Sales:", sales_data[r, c])
        print("Cost:", cost_data[r, c])
        print("Profit:", profit_data[r, c])
        print("Profit Margin:", f"{profit_margin[r, c]:.2f}%")
        print()


[[False False False False False False]
 [False False False False False False]
 [False False False False False False]
 [False False False False False False]
 [False False False False False False]]
[] []
No store-category combinations have profit margin below 22%.


Part 8: Boolean Filtering
Question 41: High Sales Values
Find all sales values greater than ₹5,00,000.

In [179]:
high_sales=sales_data>500000
# print(high_sales)
print(sales_data[high_sales])

[ 850000  780000  920000 1050000  510000  690000]


Question 42: Low Sales Values
Find all sales values below ₹2,00,000.

In [180]:
import numpy as np
low_sales=sales_data<200000
print(low_sales)
low_sales_values=sales_data[low_sales]
print(low_sales_values)

[[False False False False  True False]
 [False False False False False False]
 [False False False False  True False]
 [False False False False False False]
 [False False False False  True False]]
[190000 185000 175000]


Question 43: High Profit Values
Find all store-category combinations where profit is greater than ₹1,50,000.

In [181]:
high_profits=profit_data>150000
print(profit_data[high_profits])

[210000 190000 220000 260000 160000]


Question 44: Moderate Sales Range
Find sales values between ₹2,50,000 and ₹5,00,000.

Use np.logical_and().

In [182]:
moderate_sales=np.logical_and(sales_data>=250000,sales_data<=500000)
rows,cols=np.where(moderate_sales)
for i,j in zip(rows,cols):
    print(sales_data[i,j])

420000
310000
275000
460000
295000
310000
390000
340000
260000
375000
345000
250000
290000
405000
280000


Question 45: Premium Performance
A store-category combination is considered premium when:

Sales are greater than ₹5,00,000
Profit is greater than ₹1,50,000
Find all premium-performing combinations.

In [183]:
premium_performence=np.logical_and(sales_data>500000,profit_data>150000)
rows,cols=np.where(premium_performence)
for store,category in zip(rows,cols):
    print(stores[store],categories[category])
print(rows,cols)

Bengaluru Electronics
Hyderabad Electronics
Chennai Electronics
Mumbai Electronics
Pune Electronics
[0 1 2 3 4] [0 0 0 0 0]


Question 46: Underperforming Combinations
A store-category combination is considered underperforming when:

Sales are below ₹2,50,000
Profit margin is below 25%
Find all such combinations.

In [184]:
under_performence=np.logical_and(sales_data<250000,profit_margin<25)
rows,cols=np.where(under_performence)
for store,category in zip(rows,cols):
    print(stores[store],categories[category])

Pune Furniture


Question 47: Category Performance Classification
Create a new array that classifies every sales value as:

"High" when sales are at least ₹5,00,000
"Medium" when sales are between ₹2,50,000 and ₹4,99,999
"Low" when sales are below ₹2,50,000
Use np.where() or np.select().

In [185]:
conditions=[sales_data >= 500000,
    np.logical_and(sales_data >= 250000, sales_data < 500000),
    sales_data < 250000]
choices=["High", "Medium", "Low"]
performance = np.select(conditions, choices,None)

print(performance)

[['High' 'Medium' 'Medium' 'Medium' 'Low' 'Low']
 ['High' 'Medium' 'Medium' 'Medium' 'Low' 'Low']
 ['High' 'Medium' 'Medium' 'Medium' 'Low' 'Low']
 ['High' 'High' 'Medium' 'Medium' 'Medium' 'Medium']
 ['High' 'Medium' 'Medium' 'Low' 'Low' 'Low']]


Part 9: Target-Based Analysis
Use the following category-wise monthly sales targets:

sales_targets = np.array([
    800000,  # Electronics
    450000,  # Groceries
    320000,  # Clothing
    300000,  # Furniture
    200000,  # Beauty
    230000   # Sports
])
Question 48: Target Comparison
Compare every store’s category sales against sales_targets.

Use NumPy broadcasting.

In [186]:
sales_targets = np.array([800000,450000,320000,300000,200000,230000])
target_comparison = sales_data >= sales_targets

print(target_comparison)

[[ True False False False False False]
 [False  True False  True  True  True]
 [ True False  True False False False]
 [ True  True  True  True  True  True]
 [False False False False False False]]


Question 49: Target Achievement Matrix
Create a Boolean array where:

True means the store achieved the category target
False means the store failed to achieve the target

In [187]:
sales_targets = np.array([800000,450000,320000,300000,200000,230000])
target_comparison = sales_data >= sales_targets

print(target_comparison)

[[ True False False False False False]
 [False  True False  True  True  True]
 [ True False  True False False False]
 [ True  True  True  True  True  True]
 [False False False False False False]]


Question 50: Target Achievement Count
Calculate the number of categories in which each store achieved its target.

In [188]:
target_achievement = sales_data >= sales_targets

achievement_count = np.sum(target_achievement, axis=1)

print(achievement_count)
for i,j in zip(stores,achievement_count):
    print(i,j)

[1 4 2 6 0]
Bengaluru 1
Hyderabad 4
Chennai 2
Mumbai 6
Pune 0


Question 51: Best Target-Performing Store
Find the store that achieved the highest number of category targets.

In [189]:
target_achievement = sales_data >= sales_targets

achievement_count = np.sum(target_achievement, axis=1)

target_achived=np.argmax(achievement_count)
print(stores[target_achived])

Mumbai


Question 52: Target Achievement by Category
Calculate how many stores achieved the target for each product category.

In [190]:
sales_targets = np.array([800000,450000,320000,300000,200000,230000])
target_comparison = sales_data >= sales_targets
category_achievement_count = np.sum(target_achievement, axis=0)
for i,j in zip(stores,category_achievement_count):
    print(i,j)

Bengaluru 3
Hyderabad 2
Chennai 2
Mumbai 2
Pune 2


Question 53: Sales Target Variance
Calculate the difference between actual sales and target sales for every store.

Use:

Variance = Actual Sales - Target Sales

In [191]:
total_sales = np.sum(sales_data, axis=1)
total_target = np.sum(sales_targets)
sales_variance = total_sales - total_target
for i,j in zip(stores,sales_variance):
    print(f'{i}:{j:.2f}')
print(sales_variance)

Bengaluru:-30000.00
Hyderabad:-5000.00
Chennai:10000.00
Mumbai:520000.00
Pune:-320000.00
[ -30000   -5000   10000  520000 -320000]


Question 54: Percentage Above or Below Target
Calculate the percentage variance from the target using:

Percentage Variance =
(Actual Sales - Target Sales) / Target Sales × 100

In [192]:
total_sales = np.sum(sales_data, axis=1)
total_target = np.sum(sales_targets)
percentage_variance = ((total_sales - total_target) / total_target) * 100
for i,j in zip(stores,percentage_variance):
    print(f'{i}:{j:.2f}')
print(percentage_variance)

Bengaluru:-1.30
Hyderabad:-0.22
Chennai:0.43
Mumbai:22.61
Pune:-13.91
[ -1.30434783  -0.2173913    0.43478261  22.60869565 -13.91304348]


Question 55: Stores Missing Electronics Target
Identify stores that failed to achieve the Electronics sales target.

In [193]:
electronic_sales=np.where(categories=='Electronics')[0][0]
stores_missing=np.where(sales_data[:,electronic_sales]<sales_targets[electronic_sales])[0]
print(stores[stores_missing])

['Hyderabad' 'Pune']


Question 56: Stores Achieving All Targets
Check whether any store achieved its target in all six product categories.

Use np.all().

In [194]:
target_comparison = sales_data >= sales_targets
print(target_comparison)
all_targets = np.all(target_comparison, axis=1)
print(stores[np.where(all_targets)[0][0]],'Achived the target')
print(all_targets)

[[ True False False False False False]
 [False  True False  True  True  True]
 [ True False  True False False False]
 [ True  True  True  True  True  True]
 [False False False False False False]]
Mumbai Achived the target
[False False False  True False]


Question 57: Stores Achieving At Least One Target
Identify stores that achieved at least one category target.

Use np.any().

In [195]:
target_comparison = sales_data >= sales_targets
print(target_comparison)
all_targets = np.any(target_comparison, axis=1)
print(stores[np.where(all_targets)[0]],'Achived the target')
print(all_targets)

[[ True False False False False False]
 [False  True False  True  True  True]
 [ True False  True False False False]
 [ True  True  True  True  True  True]
 [False False False False False False]]
['Bengaluru' 'Hyderabad' 'Chennai' 'Mumbai'] Achived the target
[ True  True  True  True False]


Part 10: Discount Scenario
SmartMart plans to offer category-wise discounts:

discount_rates = np.array([
    0.10,  # Electronics: 10%
    0.05,  # Groceries: 5%
    0.15,  # Clothing: 15%
    0.12,  # Furniture: 12%
    0.08,  # Beauty: 8%
    0.10   # Sports: 10%
])
Question 58: Discount Amount Matrix
Calculate the discount amount for each store-category combination.

Use broadcasting.

In [196]:
discount_rates = np.array([0.10, 0.05, 0.15, 0.12, 0.08, 0.10 ])
discount_amount = sales_data * discount_rates

print(discount_amount)

[[ 85000.  21000.  46500.  33000.  15200.  22500.]
 [ 78000.  23000.  44250.  37200.  16800.  24000.]
 [ 92000.  19500.  51000.  31200.  14800.  21500.]
 [105000.  25500.  56250.  41400.  20000.  29000.]
 [ 69000.  20250.  42000.  27000.  14000.  20500.]]


Question 59: Sales After Discount
Calculate the net sales value after applying the category-wise discounts.

In [197]:
sales_after_discount=sales_data-discount_amount
print(sales_after_discount)

[[765000. 399000. 263500. 242000. 174800. 202500.]
 [702000. 437000. 250750. 272800. 193200. 216000.]
 [828000. 370500. 289000. 228800. 170200. 193500.]
 [945000. 484500. 318750. 303600. 230000. 261000.]
 [621000. 384750. 238000. 198000. 161000. 184500.]]


Question 60: Profit After Discount
Assuming costs remain unchanged, calculate the new profit after the discounts are applied.

In [198]:
profit_after_discount=sales_after_discount-cost_data
print(profit_after_discount)

[[125000.  84000.  43500.  37000.  49800.  42500.]
 [112000.  87000.  40750.  47800.  53200.  46000.]
 [128000.  75500.  44000.  33800.  50200.  38500.]
 [155000.  94500.  53750.  53600.  65000.  56000.]
 [ 91000.  74750.  33000.  28000.  46000.  39500.]]


Question 61: Profit Margin After Discount
Calculate the new profit margin after applying discounts.
profit_margin = (profit_data / sales_data) * 100

In [199]:
profit_margin_afterdiscount=(profit_after_discount/sales_after_discount)*100
print(profit_margin_afterdiscount)

[[16.33986928 21.05263158 16.5085389  15.2892562  28.48970252 20.98765432]
 [15.95441595 19.90846682 16.25124626 17.52199413 27.53623188 21.2962963 ]
 [15.4589372  20.37786775 15.22491349 14.77272727 29.4947121  19.89664083]
 [16.4021164  19.50464396 16.8627451  17.65480896 28.26086957 21.4559387 ]
 [14.65378422 19.42820013 13.86554622 14.14141414 28.57142857 21.40921409]]


Question 62: Loss-Making Transactions
Check whether any store-category combination becomes loss-making after discounts.

Display the affected store and category names.

In [200]:
loss_making = profit_after_discount < 0
rows, cols = np.where(loss_making)
if len(rows) == 0:
    print("No store-category combinations have profit margin below 22%.")
else:
    for r, c in zip(rows, cols):
        print("Store:", stores[r],"| Category:", categories[c])

No store-category combinations have profit margin below 22%.


Question 63: Discount Impact
Calculate how much total revenue the company loses because of the proposed discounts.

In [201]:
discount_amount = sales_data * discount_rates

total_revenue_loss = np.sum(discount_amount)

print(total_revenue_loss)
discount_amount

1146350.0


array([[ 85000.,  21000.,  46500.,  33000.,  15200.,  22500.],
       [ 78000.,  23000.,  44250.,  37200.,  16800.,  24000.],
       [ 92000.,  19500.,  51000.,  31200.,  14800.,  21500.],
       [105000.,  25500.,  56250.,  41400.,  20000.,  29000.],
       [ 69000.,  20250.,  42000.,  27000.,  14000.,  20500.]])

Question 64: Store Most Affected by Discounts
Identify the store that loses the highest amount of revenue due to discounts.

In [202]:
store_discount_loss = np.sum(discount_amount, axis=1)

# Find the store with the highest discount loss
max_index = np.argmax(store_discount_loss)

print("Store:", stores[max_index])
print("Revenue Loss:", store_discount_loss[max_index])
discount_amount

Store: Mumbai
Revenue Loss: 277150.0


array([[ 85000.,  21000.,  46500.,  33000.,  15200.,  22500.],
       [ 78000.,  23000.,  44250.,  37200.,  16800.,  24000.],
       [ 92000.,  19500.,  51000.,  31200.,  14800.,  21500.],
       [105000.,  25500.,  56250.,  41400.,  20000.,  29000.],
       [ 69000.,  20250.,  42000.,  27000.,  14000.,  20500.]])

Part 11: Tax and Price Adjustment
The government introduces category-wise tax rates:

tax_rates = np.array([
    0.18,
    0.05,
    0.12,
    0.18,
    0.18,
    0.12
])
Question 65: Tax Collection Matrix
Calculate the tax collected on sales for each store and category.

In [203]:
tax_rates = np.array([0.18,0.05,0.12,0.18,0.18,0.12])
tax_collected=tax_rates*sales_data
print(tax_collected)
# sales_data

[[153000.  21000.  37200.  49500.  34200.  27000.]
 [140400.  23000.  35400.  55800.  37800.  28800.]
 [165600.  19500.  40800.  46800.  33300.  25800.]
 [189000.  25500.  45000.  62100.  45000.  34800.]
 [124200.  20250.  33600.  40500.  31500.  24600.]]


Question 66: Sales Including Tax
Calculate the final customer billing value after adding tax.

In [204]:
final_bill=tax_collected+sales_data
print(final_bill)

[[1003000.  441000.  347200.  324500.  224200.  252000.]
 [ 920400.  483000.  330400.  365800.  247800.  268800.]
 [1085600.  409500.  380800.  306800.  218300.  240800.]
 [1239000.  535500.  420000.  407100.  295000.  324800.]
 [ 814200.  425250.  313600.  265500.  206500.  229600.]]


Question 67: Store-Wise Tax Collection
Calculate the total tax collected by each store.

In [205]:
storewise_tax=np.sum(tax_collected,axis=1)
print(storewise_tax)
for store,tax in zip(stores,storewise_tax):
    print(store , tax)

[321900. 321200. 331800. 401400. 274650.]
Bengaluru 321900.0
Hyderabad 321200.0
Chennai 331800.0
Mumbai 401400.0
Pune 274650.0


Question 68: Category-Wise Tax Collection
Calculate total tax collected for each category.

In [206]:
categorywise_tax=np.sum(tax_collected,axis=0)
print(categorywise_tax)
for category,tax in zip(categories,categorywise_tax):
    print(category , tax)

[772200. 109250. 192000. 254700. 181800. 141000.]
Electronics 772200.0
Groceries 109250.0
Clothing 192000.0
Furniture 254700.0
Beauty 181800.0
Sports 141000.0


Question 69: Highest Tax-Contributing Store
Identify the store that contributes the highest tax amount.

In [207]:
hightax_store=np.argmax(storewise_tax)
print(stores[hightax_store])

Mumbai


Part 12: Array Modification
Question 70: Updated Pune Electronics Sales
The Pune store reports that its Electronics sales were entered incorrectly.

Update Pune Electronics sales from ₹6,90,000 to ₹7,40,000.

Make the change in a copied array without modifying the original array.

In [208]:
pune_index=np.where(stores=='Mumbai')[0][0]
electronic_index=np.where(categories=='Electronics')[0][0]
updated_pune_sales=sales_data.copy()
updated_pune_sales[pune_index,electronic_index]=740000
print(updated_pune_sales)
print('before update : ',sales_data[pune_index,electronic_index])
print('after update : ',updated_pune_sales[pune_index,electronic_index])

[[850000 420000 310000 275000 190000 225000]
 [780000 460000 295000 310000 210000 240000]
 [920000 390000 340000 260000 185000 215000]
 [740000 510000 375000 345000 250000 290000]
 [690000 405000 280000 225000 175000 205000]]
before update :  1050000
after update :  740000


Question 71: Revised Beauty Cost
Due to supplier negotiations, Beauty product costs are reduced by 8% for all stores.

Create an updated cost array.

In [209]:
beauty_index=np.where(categories=='Beauty')[0][0]
updated_cost_data=cost_data.copy()
beauty_data=updated_cost_data[:,beauty_index]
updated_beauty_array=beauty_data-beauty_data*0.08
print(updated_beauty_array)
updated_cost_data[:,beauty_index]=updated_beauty_array
print('before update of beauty cost data : \n',cost_data)
print('after update of beauty cost data : \n',updated_cost_data)


[115000. 128800. 110400. 151800. 105800.]
before update of beauty cost data : 
 [[640000 315000 220000 205000 125000 160000]
 [590000 350000 210000 225000 140000 170000]
 [700000 295000 245000 195000 120000 155000]
 [790000 390000 265000 250000 165000 205000]
 [530000 310000 205000 170000 115000 145000]]
after update of beauty cost data : 
 [[640000 315000 220000 205000 115000 160000]
 [590000 350000 210000 225000 128800 170000]
 [700000 295000 245000 195000 110400 155000]
 [790000 390000 265000 250000 151800 205000]
 [530000 310000 205000 170000 105800 145000]]


Question 72: Furniture Cost Increase
Furniture costs increase by 12% for all stores.

Update only the Furniture column.

In [210]:
furniture_index=np.where(categories=='Furniture')[0][0]
updated_cost_data=cost_data.copy()
furniture_data=updated_cost_data[:,furniture_index]
updated_furniture_array=furniture_data+(furniture_data*0.12)
print(updated_furniture_array)
updated_cost_data[:,furniture_index]=updated_furniture_array
print('before update of furniture cost data : \n',cost_data)
print('after update of furniturre cost data : \n',updated_cost_data)

[229600. 252000. 218400. 280000. 190400.]
before update of furniture cost data : 
 [[640000 315000 220000 205000 125000 160000]
 [590000 350000 210000 225000 140000 170000]
 [700000 295000 245000 195000 120000 155000]
 [790000 390000 265000 250000 165000 205000]
 [530000 310000 205000 170000 115000 145000]]
after update of furniturre cost data : 
 [[640000 315000 220000 229600 125000 160000]
 [590000 350000 210000 252000 140000 170000]
 [700000 295000 245000 218400 120000 155000]
 [790000 390000 265000 280000 165000 205000]
 [530000 310000 205000 190400 115000 145000]]


Question 73: Store Closure Simulation
Assume the Pune store is temporarily closed.

Remove Pune’s sales and cost data from the analysis using np.delete().

In [211]:
pune_index=np.where(stores=='Pune')[0][0]
sales_without_pune=np.delete(sales_data,pune_index,axis=0)
cost_without_pune=np.delete(cost_data,pune_index,axis=0)
print("Sales without Pune:")
print(sales_without_pune)

print("\nCost without Pune:")
print(cost_without_pune)

Sales without Pune:
[[ 850000  420000  310000  275000  190000  225000]
 [ 780000  460000  295000  310000  210000  240000]
 [ 920000  390000  340000  260000  185000  215000]
 [1050000  510000  375000  345000  250000  290000]]

Cost without Pune:
[[640000 315000 220000 205000 125000 160000]
 [590000 350000 210000 225000 140000 170000]
 [700000 295000 245000 195000 120000 155000]
 [790000 390000 265000 250000 165000 205000]]


Question 74: Adding a New Store
A new Delhi store is opened with the following data:

delhi_sales = np.array([
    880000, 475000, 330000, 290000, 215000, 250000
])

delhi_cost = np.array([
    665000, 360000, 235000, 215000, 145000, 180000
])
Add Delhi to both arrays using np.vstack().

Also add "Delhi" to the stores array.

In [212]:
delhi_sales = np.array([
    880000, 475000, 330000, 290000, 215000, 250000
])
delhi_cost = np.array([
    665000, 360000, 235000, 215000, 145000, 180000
])
new_sales_data = np.vstack((sales_data, delhi_sales))
new_cost_data = np.vstack((cost_data, delhi_cost))
new_stores = np.append(stores, "Delhi")
print(new_stores)
print(new_sales_data)
print(new_cost_data)

['Bengaluru' 'Hyderabad' 'Chennai' 'Mumbai' 'Pune' 'Delhi']
[[ 850000  420000  310000  275000  190000  225000]
 [ 780000  460000  295000  310000  210000  240000]
 [ 920000  390000  340000  260000  185000  215000]
 [1050000  510000  375000  345000  250000  290000]
 [ 690000  405000  280000  225000  175000  205000]
 [ 880000  475000  330000  290000  215000  250000]]
[[640000 315000 220000 205000 125000 160000]
 [590000 350000 210000 225000 140000 170000]
 [700000 295000 245000 195000 120000 155000]
 [790000 390000 265000 250000 165000 205000]
 [530000 310000 205000 170000 115000 145000]
 [665000 360000 235000 215000 145000 180000]]


Question 75: Adding a New Product Category
SmartMart starts selling Home Appliances.

home_appliance_sales = np.array([
    360000,
    325000,
    390000,
    420000,
    295000
])

home_appliance_cost = np.array([
    265000,
    240000,
    285000,
    305000,
    225000
])
Add the new category as a column using np.column_stack() or np.hstack()

In [213]:
home_appliance_sales = np.array([360000,325000,390000,420000,295000])
home_appliance_cost = np.array([265000,240000,285000,305000,225000])
new_categories=np.append(categories,'home_appliance')
new_categories_sales=np.column_stack((sales_data,home_appliance_sales))
new_categories_cost=np.column_stack((cost_data,home_appliance_cost))
print(new_categories)
print(new_categories_sales)
print(new_categories_cost)

['Electronics' 'Groceries' 'Clothing' 'Furniture' 'Beauty' 'Sports'
 'home_appliance']
[[ 850000  420000  310000  275000  190000  225000  360000]
 [ 780000  460000  295000  310000  210000  240000  325000]
 [ 920000  390000  340000  260000  185000  215000  390000]
 [1050000  510000  375000  345000  250000  290000  420000]
 [ 690000  405000  280000  225000  175000  205000  295000]]
[[640000 315000 220000 205000 125000 160000 265000]
 [590000 350000 210000 225000 140000 170000 240000]
 [700000 295000 245000 195000 120000 155000 285000]
 [790000 390000 265000 250000 165000 205000 305000]
 [530000 310000 205000 170000 115000 145000 225000]]


Part 13: Sorting and Ranking
Question 76: Sort Stores by Sales
Sort stores in ascending order based on total sales.

Display store names and sales totals.

In [214]:
store_sales = np.sum(sales_data, axis=1)

sorted_indices = np.argsort(store_sales)

for i in sorted_indices:
    print(stores[i], ":", store_sales[i])

Pune : 1980000
Bengaluru : 2270000
Hyderabad : 2295000
Chennai : 2310000
Mumbai : 2820000


Question 77: Rank Stores by Profit
Rank stores from highest to lowest total profit.

Use np.argsort().

In [215]:
profit_data=sales_data - cost_data
store_profit = np.sum(profit_data, axis=1)
store_sorted_indices=np.argsort(store_profit)[::-1]
for i in store_sorted_indices:
    print(f'{categories[i]} : {store_profit[i]}')

Furniture : 755000
Groceries : 610000
Electronics : 605000
Clothing : 600000
Beauty : 505000


Question 78: Sort Categories by Revenue
Sort product categories from highest to lowest total revenue.

In [216]:
revenue=np.sum(sales_data,axis=0)
sorted_revenue_indices=np.argsort(revenue)[::-1]
for i in sorted_revenue_indices:
    print(categories[i] , sorted_revenue_indices[i])

Electronics 0
Groceries 1
Clothing 2
Furniture 3
Sports 4
Beauty 5


Question 79: Top Three Store-Category Sales
Find the three highest individual sales values in the complete sales matrix.

Display their:

Sales value
Store name
Category name

In [217]:
# Find the indices of the top 3 sales values
flat_indices = np.argsort(sales_data.ravel())[-3:][::-1]

# Convert flattened indices back to row and column indices
rows, cols = np.unravel_index(flat_indices, sales_data.shape)

# Display results
for r, c in zip(rows, cols):
    print("Sales:", sales_data[r, c],
          "| Store:", stores[r],
          "| Category:", categories[c])

Sales: 1050000 | Store: Mumbai | Category: Electronics
Sales: 920000 | Store: Chennai | Category: Electronics
Sales: 850000 | Store: Bengaluru | Category: Electronics


Question 80: Bottom Three Profits
Find the three lowest profit values in the profit matrix.

In [218]:
flat_profit = profit_data.ravel()

lowest_indices = np.argsort(flat_profit)[:3]

rows, cols = np.unravel_index(
    lowest_indices,
    profit_data.shape
)

for r, c in zip(rows, cols):
    print(
        "Profit:", profit_data[r, c],
        "| Store:", stores[r],
        "| Category:", categories[c]
    )

Profit: 55000 | Store: Pune | Category: Furniture
Profit: 60000 | Store: Pune | Category: Sports
Profit: 60000 | Store: Chennai | Category: Sports


Part 14: Statistical Analysis
Question 81: Sales Statistics
Calculate the following for the complete sales array:

Minimum
Maximum
Mean
Median
Standard deviation
Variance
25th percentile
50th percentile
75th percentile

In [219]:
print("Minimum:", np.min(sales_data))
print("Maximum:", np.max(sales_data))
print("Mean:", np.mean(sales_data))
print("Median:", np.median(sales_data))
print("Standard Deviation:", np.std(sales_data))
print("Variance:", np.var(sales_data))
print("25th Percentile:", np.percentile(sales_data, 25))
print("50th Percentile:", np.percentile(sales_data, 50))
print("75th Percentile:", np.percentile(sales_data, 75))

Minimum: 175000
Maximum: 1050000
Mean: 389166.6666666667
Median: 302500.0
Standard Deviation: 230322.53954448793
Variance: 53048472222.222206
25th Percentile: 228750.0
50th Percentile: 302500.0
75th Percentile: 416250.0


Question 82: Store-Wise Standard Deviation
Calculate the sales standard deviation for every store.

Use this value to determine which store has the most variation between product categories.

In [220]:
store_std=np.std(sales_data,axis=1)
for store,std in zip(stores,store_std):
    print(f'{store} : {std:.2f}')

Bengaluru : 223059.53
Hyderabad : 194502.57
Chennai : 249265.59
Mumbai : 271860.87
Pune : 177200.45



Question 83: Category-Wise Standard Deviation
Determine which product category has the highest variation in sales across stores.

In [221]:
categories

array(['Electronics', 'Groceries', 'Clothing', 'Furniture', 'Beauty',
       'Sports'], dtype='<U11')

In [222]:
category_std=np.std(sales_data,axis=0)
for category,std in zip(categories,category_std):
    print(f'{category} : {std:.2f}')

Electronics : 122539.79
Groceries : 43312.82
Clothing : 33911.65
Furniture : 41303.75
Beauty : 26570.66
Sports : 29832.87


Question 84: Sales Above Company Average
Calculate the company-wide average sales value.

Count how many store-category sales values are above this average.

In [223]:
# Company-wide average sales
company_average = np.mean(sales_data)

# Count sales values above the average
count_above_average = np.sum(sales_data > company_average)

print("Company Average Sales:", company_average)
print("Count Above Average:", count_above_average)

Company Average Sales: 389166.6666666667
Count Above Average: 10


Question 85: Outlier Detection
Treat any sales value greater than:

Mean + 1.5 × Standard Deviation
as a high-value outlier.

Identify all such sales values.

In [224]:
# Calculate mean and standard deviation
mean_sales = np.mean(sales_data)
std_sales = np.std(sales_data)

# Outlier threshold
threshold = mean_sales + 1.5 * std_sales

print("Mean:", mean_sales)
print("Standard Deviation:", std_sales)
print("Threshold:", threshold)

# Find outlier sales values
outliers = sales_data[sales_data > threshold]

print("High-value outliers:", outliers)

Mean: 389166.6666666667
Standard Deviation: 230322.53954448793
Threshold: 734650.4759833985
High-value outliers: [ 850000  780000  920000 1050000]


Part 15: Reshaping and Transformation
Question 86: Flatten Sales Data
Convert the two-dimensional sales array into a one-dimensional array using:

flatten()
ravel()
Explain the difference between the two methods.

In [225]:
sales_flatten = sales_data.flatten()

print(sales_flatten)
sales_ravel = sales_data.ravel()

print(sales_ravel)
# flatten() → creates a new copy
# ravel()   → returns a flattened view when possible

[ 850000  420000  310000  275000  190000  225000  780000  460000  295000
  310000  210000  240000  920000  390000  340000  260000  185000  215000
 1050000  510000  375000  345000  250000  290000  690000  405000  280000
  225000  175000  205000]
[ 850000  420000  310000  275000  190000  225000  780000  460000  295000
  310000  210000  240000  920000  390000  340000  260000  185000  215000
 1050000  510000  375000  345000  250000  290000  690000  405000  280000
  225000  175000  205000]


Question 87: Reshape Sales Data
Reshape the 5 × 6 sales array into:

3 × 10
10 × 3
2 × 15
15 × 2
Verify that no data is lost.

In [226]:
sales_3x10 = sales_data.reshape(3, 10)
sales_10x3 = sales_data.reshape(10, 3)
sales_2x15 = sales_data.reshape(2, 15)
sales_15x2 = sales_data.reshape(15, 2)

print("3 × 10:\n", sales_3x10)
print("\n10 × 3:\n", sales_10x3)
print("\n2 × 15:\n", sales_2x15)
print("\n15 × 2:\n", sales_15x2)
print(sales_data.size)
print(sales_3x10.size)
print(sales_10x3.size)
print(sales_2x15.size)
print(sales_15x2.size)

3 × 10:
 [[ 850000  420000  310000  275000  190000  225000  780000  460000  295000
   310000]
 [ 210000  240000  920000  390000  340000  260000  185000  215000 1050000
   510000]
 [ 375000  345000  250000  290000  690000  405000  280000  225000  175000
   205000]]

10 × 3:
 [[ 850000  420000  310000]
 [ 275000  190000  225000]
 [ 780000  460000  295000]
 [ 310000  210000  240000]
 [ 920000  390000  340000]
 [ 260000  185000  215000]
 [1050000  510000  375000]
 [ 345000  250000  290000]
 [ 690000  405000  280000]
 [ 225000  175000  205000]]

2 × 15:
 [[ 850000  420000  310000  275000  190000  225000  780000  460000  295000
   310000  210000  240000  920000  390000  340000]
 [ 260000  185000  215000 1050000  510000  375000  345000  250000  290000
   690000  405000  280000  225000  175000  205000]]

15 × 2:
 [[ 850000  420000]
 [ 310000  275000]
 [ 190000  225000]
 [ 780000  460000]
 [ 295000  310000]
 [ 210000  240000]
 [ 920000  390000]
 [ 340000  260000]
 [ 185000  215000]
 [1050000  5

Question 88: Transpose Sales Data
Transpose the sales array so that:

Rows represent product categories
Columns represent stores
Display the new shape.

In [227]:
sales_transposed = sales_data.T

print(sales_transposed)
print("New shape:", sales_transposed.shape)

[[ 850000  780000  920000 1050000  690000]
 [ 420000  460000  390000  510000  405000]
 [ 310000  295000  340000  375000  280000]
 [ 275000  310000  260000  345000  225000]
 [ 190000  210000  185000  250000  175000]
 [ 225000  240000  215000  290000  205000]]
New shape: (6, 5)


Question 89: Combined Sales and Cost Array
Stack sales_data and cost_data vertically.

Display the resulting shape.

In [228]:
stack=np.vstack((sales_data,cost_data))
print(stack)
stack.shape
# np.column_stack((sales_data,cost_data))


[[ 850000  420000  310000  275000  190000  225000]
 [ 780000  460000  295000  310000  210000  240000]
 [ 920000  390000  340000  260000  185000  215000]
 [1050000  510000  375000  345000  250000  290000]
 [ 690000  405000  280000  225000  175000  205000]
 [ 640000  315000  220000  205000  125000  160000]
 [ 590000  350000  210000  225000  140000  170000]
 [ 700000  295000  245000  195000  120000  155000]
 [ 790000  390000  265000  250000  165000  205000]
 [ 530000  310000  205000  170000  115000  145000]]


(10, 6)

Question 90: Store-Level Combined Data
Create a three-dimensional array where:

First layer contains sales data
Second layer contains cost data
Use np.stack().

Display the shape of the new array.

In [229]:
combined_data = np.stack((sales_data, cost_data))

print(combined_data)
print("Shape:", combined_data.shape)

[[[ 850000  420000  310000  275000  190000  225000]
  [ 780000  460000  295000  310000  210000  240000]
  [ 920000  390000  340000  260000  185000  215000]
  [1050000  510000  375000  345000  250000  290000]
  [ 690000  405000  280000  225000  175000  205000]]

 [[ 640000  315000  220000  205000  125000  160000]
  [ 590000  350000  210000  225000  140000  170000]
  [ 700000  295000  245000  195000  120000  155000]
  [ 790000  390000  265000  250000  165000  205000]
  [ 530000  310000  205000  170000  115000  145000]]]
Shape: (2, 5, 6)


Part 16: Missing Data Scenario
The company discovers that some sales values were not recorded.

sales_with_missing = np.array([
    [850000, 420000, np.nan, 275000, 190000, 225000],
    [780000, 460000, 295000, np.nan, 210000, 240000],
    [920000, 390000, 340000, 260000, 185000, 215000],
    [1050000, np.nan, 375000, 345000, 250000, 290000],
    [690000, 405000, 280000, 225000, np.nan, 205000]
])
Question 91: Missing Value Detection
Find:

Total number of missing values
Location of missing values
Stores and categories containing missing values

In [230]:
sales_with_missing = np.array([
    [850000, 420000, np.nan, 275000, 190000, 225000],
    [780000, 460000, 295000, np.nan, 210000, 240000],
    [920000, 390000, 340000, 260000, 185000, 215000],
    [1050000, np.nan, 375000, 345000, 250000, 290000],
    [690000, 405000, 280000, 225000, np.nan, 205000]
])
missing=np.isnan(sales_with_missing)
total_missing = np.sum(np.isnan(sales_with_missing))
print(total_missing)
rows,cols=np.where(np.isnan(sales_with_missing))
print("Rows:", rows)
print("Columns:", cols)
for r, c in zip(rows, cols):
    print("Store:", stores[r],"| Category:", categories[c])

4
Rows: [0 1 3 4]
Columns: [2 3 1 4]
Store: Bengaluru | Category: Clothing
Store: Hyderabad | Category: Furniture
Store: Mumbai | Category: Groceries
Store: Pune | Category: Beauty


Question 92: Replace Missing Values with Zero
Replace all missing sales values with zero.

In [231]:
sales_filled = sales_with_missing.copy()
sales_filled[np.isnan(sales_filled)] = 0
# sales_filled = np.nan_to_num(sales_with_missing, nan=0)

print(sales_filled)

[[ 850000.  420000.       0.  275000.  190000.  225000.]
 [ 780000.  460000.  295000.       0.  210000.  240000.]
 [ 920000.  390000.  340000.  260000.  185000.  215000.]
 [1050000.       0.  375000.  345000.  250000.  290000.]
 [ 690000.  405000.  280000.  225000.       0.  205000.]]


Question 93: Replace with Company Average
Replace missing values with the overall average of available sales values.

Use np.nanmean().

In [232]:
company_average = np.nanmean(sales_with_missing)

sales_filled = np.where(
    np.isnan(sales_with_missing),
    company_average,
    sales_with_missing
)
print("Company Average:", company_average)
print(np.round(sales_filled, 2))

Company Average: 398846.1538461539
[[ 850000.    420000.    398846.15  275000.    190000.    225000.  ]
 [ 780000.    460000.    295000.    398846.15  210000.    240000.  ]
 [ 920000.    390000.    340000.    260000.    185000.    215000.  ]
 [1050000.    398846.15  375000.    345000.    250000.    290000.  ]
 [ 690000.    405000.    280000.    225000.    398846.15  205000.  ]]


Question 94: Replace with Category Average
Replace each missing value with the average sales value of its respective product category.

In [233]:
# Calculate average for each category
category_avg = np.nanmean(sales_with_missing, axis=0)

print("Category averages:")
print(category_avg)

# Replace NaN with the respective category average
sales_filled = np.where(
    np.isnan(sales_with_missing),
    category_avg,
    sales_with_missing
)

print("\nUpdated sales data:")
print(np.round(sales_filled, 2))

Category averages:
[858000. 418750. 322500. 276250. 208750. 235000.]

Updated sales data:
[[ 850000.  420000.  322500.  275000.  190000.  225000.]
 [ 780000.  460000.  295000.  276250.  210000.  240000.]
 [ 920000.  390000.  340000.  260000.  185000.  215000.]
 [1050000.  418750.  375000.  345000.  250000.  290000.]
 [ 690000.  405000.  280000.  225000.  208750.  205000.]]


Question 95: Missing Value Impact
Compare total sales before and after replacing missing values with zero.

In [234]:
# Total sales before replacing missing values
total_before = np.nansum(sales_with_missing)

# Replace missing values with zero
sales_zero = np.nan_to_num(sales_with_missing, nan=0)

# Total sales after replacing missing values with zero
total_after = np.sum(sales_zero)

print("Total Sales Before:", total_before)
print("Total Sales After:", total_after)
print("Difference:", total_before - total_after)

Total Sales Before: 10370000.0
Total Sales After: 10370000.0
Difference: 0.0


Part 17: Conditional Business Decisions
Question 96: Store Performance Labels
Classify each store based on total sales:

"Excellent": Total sales above ₹28,00,000
"Good": Total sales between ₹24,00,000 and ₹28,00,000
"Needs Improvement": Total sales below ₹24,00,000
Use np.select().

In [235]:
sales_zero = np.nan_to_num(sales_with_missing, nan=0)
total_after = np.sum(sales_zero)
conditions=[store_sales > 2800000,(store_sales >= 2400000) & (store_sales <= 2800000),store_sales < 2400000]
labels = ["Excellent","Good","Needs Improvement"]
performance = np.select(conditions,labels,None)
for store, sales, label in zip(stores, store_sales, performance):
    print(store, ":", sales, "→", label)


Bengaluru : 2270000 → Needs Improvement
Hyderabad : 2295000 → Needs Improvement
Chennai : 2310000 → Needs Improvement
Mumbai : 2820000 → Excellent
Pune : 1980000 → Needs Improvement


Question 97: Profitability Classification
Classify each store-category combination as:

"Highly Profitable": Profit above ₹2,00,000
"Profitable": Profit between ₹1,00,000 and ₹2,00,000
"Low Profit": Profit below ₹1,00,000
"Loss": Profit below zero

In [236]:
profit_data = sales_data - cost_data
conditions = [
    profit_data < 0,
    profit_data < 100000,
    profit_data <= 200000,
    profit_data > 200000
]

labels = [
    "Loss",
    "Low Profit",
    "Profitable",
    "Highly Profitable"
]

profit_classification = np.select(conditions,labels,None)

# print(profit_classification)
for i in range(len(stores)):
    for j in range(len(categories)):
        print(stores[i],"|",categories[j],"| Profit:", profit_data[i, j],"|", profit_classification[i, j])

Bengaluru | Electronics | Profit: 210000 | Highly Profitable
Bengaluru | Groceries | Profit: 105000 | Profitable
Bengaluru | Clothing | Profit: 90000 | Low Profit
Bengaluru | Furniture | Profit: 70000 | Low Profit
Bengaluru | Beauty | Profit: 65000 | Low Profit
Bengaluru | Sports | Profit: 65000 | Low Profit
Hyderabad | Electronics | Profit: 190000 | Profitable
Hyderabad | Groceries | Profit: 110000 | Profitable
Hyderabad | Clothing | Profit: 85000 | Low Profit
Hyderabad | Furniture | Profit: 85000 | Low Profit
Hyderabad | Beauty | Profit: 70000 | Low Profit
Hyderabad | Sports | Profit: 70000 | Low Profit
Chennai | Electronics | Profit: 220000 | Highly Profitable
Chennai | Groceries | Profit: 95000 | Low Profit
Chennai | Clothing | Profit: 95000 | Low Profit
Chennai | Furniture | Profit: 65000 | Low Profit
Chennai | Beauty | Profit: 65000 | Low Profit
Chennai | Sports | Profit: 60000 | Low Profit
Mumbai | Electronics | Profit: 260000 | Highly Profitable
Mumbai | Groceries | Profit: 120

Question 98: Expansion Recommendation
A store is eligible for expansion when:

Total sales are above ₹25,00,000
Total profit is above ₹7,00,000
Overall profit margin is above 25%
Identify eligible stores.

In [237]:
# Total sales for each store
store_sales = np.sum(sales_data, axis=1)

# Total profit for each store
profit_data = sales_data - cost_data
store_profit = np.sum(profit_data, axis=1)

# Overall profit margin for each store
profit_margin = (store_profit / store_sales) * 100

# Expansion condition
eligible = ((store_sales > 2500000) & (store_profit > 700000) & (profit_margin > 25))

# Display results
for i in range(len(stores)):
    print(stores[i],"| Sales:", store_sales[i],"| Profit:", store_profit[i],"| Margin:", round(profit_margin[i], 2), "%",
    "| Expansion:", "Eligible" if eligible[i] else "Not Eligible"
    )

Bengaluru | Sales: 2270000 | Profit: 605000 | Margin: 26.65 % | Expansion: Not Eligible
Hyderabad | Sales: 2295000 | Profit: 610000 | Margin: 26.58 % | Expansion: Not Eligible
Chennai | Sales: 2310000 | Profit: 600000 | Margin: 25.97 % | Expansion: Not Eligible
Mumbai | Sales: 2820000 | Profit: 755000 | Margin: 26.77 % | Expansion: Eligible
Pune | Sales: 1980000 | Profit: 505000 | Margin: 25.51 % | Expansion: Not Eligible


Question 99: Category Promotion Recommendation
A product category should receive additional promotion when:

Average sales are below ₹3,00,000
Profit margin is above 25%
Identify the categories that satisfy these conditions.

In [238]:
# Profit data
profit_data = sales_data - cost_data

# Average sales for each category
category_avg_sales = np.mean(sales_data, axis=0)

# Total sales for each category
category_sales = np.sum(sales_data, axis=0)

# Total profit for each category
category_profit = np.sum(profit_data, axis=0)

# Profit margin for each category
category_profit_margin = (category_profit / category_sales) * 100
conditions = [(category_avg_sales < 300000) &(category_profit_margin > 25)]

# Check which categories qualify
promotion = conditions[0]

for i in range(len(categories)):
    print(categories[i],"| Average Sales:", category_avg_sales[i],"| Profit Margin:", round(category_profit_margin[i], 2), "%",
        "| Promotion:", "Yes" if promotion[i] else "No")

Electronics | Average Sales: 858000.0 | Profit Margin: 24.24 % | Promotion: No
Groceries | Average Sales: 437000.0 | Profit Margin: 24.03 % | Promotion: No
Clothing | Average Sales: 320000.0 | Profit Margin: 28.44 % | Promotion: No
Furniture | Average Sales: 283000.0 | Profit Margin: 26.15 % | Promotion: Yes
Beauty | Average Sales: 202000.0 | Profit Margin: 34.16 % | Promotion: Yes
Sports | Average Sales: 235000.0 | Profit Margin: 28.94 % | Promotion: Yes


Question 100: Cost Optimization Recommendation
Find store-category combinations where:

Cost is greater than ₹2,50,000
Profit margin is below 25%
These combinations should be reviewed for cost optimization.

In [239]:
profit_data = sales_data - cost_data

profit_margin = (profit_data / sales_data) * 100

condition = (cost_data > 250000) & (profit_margin < 25)

rows, cols = np.where(condition)

for r, c in zip(rows, cols):
    print("Store:", stores[r],"| Category:", categories[c],"| Cost:", cost_data[r, c],
        "| Profit Margin:", round(profit_margin[r, c], 2), "%")

Store: Bengaluru | Category: Electronics | Cost: 640000 | Profit Margin: 24.71 %
Store: Hyderabad | Category: Electronics | Cost: 590000 | Profit Margin: 24.36 %
Store: Hyderabad | Category: Groceries | Cost: 350000 | Profit Margin: 23.91 %
Store: Chennai | Category: Electronics | Cost: 700000 | Profit Margin: 23.91 %
Store: Chennai | Category: Groceries | Cost: 295000 | Profit Margin: 24.36 %
Store: Mumbai | Category: Electronics | Cost: 790000 | Profit Margin: 24.76 %
Store: Mumbai | Category: Groceries | Cost: 390000 | Profit Margin: 23.53 %
Store: Pune | Category: Electronics | Cost: 530000 | Profit Margin: 23.19 %
Store: Pune | Category: Groceries | Cost: 310000 | Profit Margin: 23.46 %


Part 18: Inventory Scenario
Use the following inventory arrays:

opening_stock = np.array([
    [120, 450, 300, 90, 250, 180],
    [110, 500, 280, 100, 270, 200],
    [130, 420, 320, 85, 240, 170],
    [150, 550, 350, 120, 300, 220],
    [100, 400, 260, 75, 220, 160]
])

units_sold = np.array([
    [95, 380, 240, 65, 190, 140],
    [85, 420, 230, 75, 210, 155],
    [105, 350, 270, 60, 180, 130],
    [125, 470, 295, 90, 235, 175],
    [75, 330, 205, 55, 165, 120]
])
Question 101: Closing Stock
Calculate closing stock using:

Closing Stock = Opening Stock - Units Sold

In [240]:
opening_stock = np.array([
    [120, 450, 300, 90, 250, 180],
    [110, 500, 280, 100, 270, 200],
    [130, 420, 320, 85, 240, 170],
    [150, 550, 350, 120, 300, 220],
    [100, 400, 260, 75, 220, 160]
])

units_sold = np.array([
    [95, 380, 240, 65, 190, 140],
    [85, 420, 230, 75, 210, 155],
    [105, 350, 270, 60, 180, 130],
    [125, 470, 295, 90, 235, 175],
    [75, 330, 205, 55, 165, 120]
])
closing_stock = opening_stock - units_sold

print(closing_stock)

[[25 70 60 25 60 40]
 [25 80 50 25 60 45]
 [25 70 50 25 60 40]
 [25 80 55 30 65 45]
 [25 70 55 20 55 40]]



Question 102: Low-Stock Identification
Identify store-category combinations where closing stock is below 30 units.

In [241]:
rows, cols = np.where(closing_stock < 30)
for r, c in zip(rows, cols):
    print("Store:", stores[r],"| Category:", categories[c],"| Closing Stock:", closing_stock[r, c])

Store: Bengaluru | Category: Electronics | Closing Stock: 25
Store: Bengaluru | Category: Furniture | Closing Stock: 25
Store: Hyderabad | Category: Electronics | Closing Stock: 25
Store: Hyderabad | Category: Furniture | Closing Stock: 25
Store: Chennai | Category: Electronics | Closing Stock: 25
Store: Chennai | Category: Furniture | Closing Stock: 25
Store: Mumbai | Category: Electronics | Closing Stock: 25
Store: Pune | Category: Electronics | Closing Stock: 25
Store: Pune | Category: Furniture | Closing Stock: 20


Question 103: Stock Availability Percentage
Calculate the percentage of opening stock that remains unsold.

In [242]:
stock_unsold=opening_stock-units_sold
# print(stock_unsold)
percentage=(stock_unsold/opening_stock)*100
print(np.round(percentage,2))

[[20.83 15.56 20.   27.78 24.   22.22]
 [22.73 16.   17.86 25.   22.22 22.5 ]
 [19.23 16.67 15.62 29.41 25.   23.53]
 [16.67 14.55 15.71 25.   21.67 20.45]
 [25.   17.5  21.15 26.67 25.   25.  ]]


Question 104: Fast-Moving Products
A product is considered fast-moving when more than 80% of its opening stock has been sold.

Identify fast-moving store-category combinations.

In [243]:
sold_percentage = (units_sold / opening_stock) * 100
rows, cols = np.where(sold_percentage > 80)

for r, c in zip(rows, cols):
    print("Store:", stores[r],"| Category:", categories[c],"| Sold:", units_sold[r, c], "| Opening:", opening_stock[r, c],
        "| Sold %:", round(sold_percentage[r, c], 2), "%")

Store: Bengaluru | Category: Groceries | Sold: 380 | Opening: 450 | Sold %: 84.44 %
Store: Hyderabad | Category: Groceries | Sold: 420 | Opening: 500 | Sold %: 84.0 %
Store: Hyderabad | Category: Clothing | Sold: 230 | Opening: 280 | Sold %: 82.14 %
Store: Chennai | Category: Electronics | Sold: 105 | Opening: 130 | Sold %: 80.77 %
Store: Chennai | Category: Groceries | Sold: 350 | Opening: 420 | Sold %: 83.33 %
Store: Chennai | Category: Clothing | Sold: 270 | Opening: 320 | Sold %: 84.38 %
Store: Mumbai | Category: Electronics | Sold: 125 | Opening: 150 | Sold %: 83.33 %
Store: Mumbai | Category: Groceries | Sold: 470 | Opening: 550 | Sold %: 85.45 %
Store: Mumbai | Category: Clothing | Sold: 295 | Opening: 350 | Sold %: 84.29 %
Store: Pune | Category: Groceries | Sold: 330 | Opening: 400 | Sold %: 82.5 %


Question 105: Category-Wise Units Sold
Calculate the total units sold for each product category.

In [244]:
category_units_sold = np.sum(units_sold, axis=0)

for i in range(len(categories)):
    print(categories[i], ":", category_units_sold[i])

Electronics : 485
Groceries : 1950
Clothing : 1240
Furniture : 345
Beauty : 980
Sports : 720


Question 106: Store-Wise Units Sold
Calculate total units sold by each store.

In [245]:
store_units_sold = np.sum(units_sold, axis=1)

for i in range(len(stores)):
    print(stores[i], ":", store_units_sold[i])

Bengaluru : 1110
Hyderabad : 1175
Chennai : 1095
Mumbai : 1390
Pune : 950



Question 107: Best Store by Unit Sales
Identify the store that sold the highest total number of units.

In [246]:
best_index = np.argmax(store_units_sold)

print("Best Store:", stores[best_index])
print("Total Units Sold:", store_units_sold[best_index])

Best Store: Mumbai
Total Units Sold: 1390


Question 108: Reorder Requirement
A store should reorder a category when closing stock is below 25 units.

Create a Boolean reorder matrix.

In [247]:
reorder = closing_stock < 25

print(reorder)

[[False False False False False False]
 [False False False False False False]
 [False False False False False False]
 [False False False False False False]
 [False False False  True False False]]


Question 109: Reorder Quantity
Assume each category must maintain 100 units after reordering.

Calculate reorder quantities only for combinations where closing stock is below 25.

For all other combinations, return zero.

In [248]:
reorder_quantity = np.where(
    closing_stock < 25,
    100 - closing_stock,0)

print(reorder_quantity)

[[ 0  0  0  0  0  0]
 [ 0  0  0  0  0  0]
 [ 0  0  0  0  0  0]
 [ 0  0  0  0  0  0]
 [ 0  0  0 80  0  0]]


Part 19: Advanced NumPy Questions
Question 110: Cumulative Store Sales
Calculate cumulative category sales for each store using np.cumsum().

In [249]:
cumulative_sales = np.cumsum(sales_data, axis=1)

print(cumulative_sales)

[[ 850000 1270000 1580000 1855000 2045000 2270000]
 [ 780000 1240000 1535000 1845000 2055000 2295000]
 [ 920000 1310000 1650000 1910000 2095000 2310000]
 [1050000 1560000 1935000 2280000 2530000 2820000]
 [ 690000 1095000 1375000 1600000 1775000 1980000]]


Question 111: Cumulative Company Sales
Flatten the sales array and calculate cumulative company sales.

In [250]:
# Flatten sales data
sales_flat = sales_data.flatten()

# Calculate cumulative company sales
cumulative_company_sales = np.cumsum(sales_flat)

print(cumulative_company_sales)

[  850000  1270000  1580000  1855000  2045000  2270000  3050000  3510000
  3805000  4115000  4325000  4565000  5485000  5875000  6215000  6475000
  6660000  6875000  7925000  8435000  8810000  9155000  9405000  9695000
 10385000 10790000 11070000 11295000 11470000 11675000]


Question 112: Sales Difference Between Categories
Calculate the difference between consecutive category sales for each store using np.diff().

In [251]:
category_difference = np.diff(sales_data, axis=1)

print(category_difference)

[[-430000 -110000  -35000  -85000   35000]
 [-320000 -165000   15000 -100000   30000]
 [-530000  -50000  -80000  -75000   30000]
 [-540000 -135000  -30000  -95000   40000]
 [-285000 -125000  -55000  -50000   30000]]


In [252]:
unique_values, frequency = np.unique(
    sales_data,
    return_counts=True
)

for value, count in zip(unique_values, frequency):
    print(value, ":", count)

175000 : 1
185000 : 1
190000 : 1
205000 : 1
210000 : 1
215000 : 1
225000 : 2
240000 : 1
250000 : 1
260000 : 1
275000 : 1
280000 : 1
290000 : 1
295000 : 1
310000 : 2
340000 : 1
345000 : 1
375000 : 1
390000 : 1
405000 : 1
420000 : 1
460000 : 1
510000 : 1
690000 : 1
780000 : 1
850000 : 1
920000 : 1
1050000 : 1


Question 114: Search for Specific Sales
Check whether the value ₹4,20,000 exists in the sales array.

Return its location.

In [253]:
value = 420000

rows, cols = np.where(sales_data == value)

print("Rows:", rows)
print("Columns:", cols)

Rows: [0]
Columns: [1]


Question 115: Compare Sales and Cost
Create a Boolean array showing whether sales are greater than cost for every combination.

Verify whether all combinations are profitable using np.all().

In [254]:
# Check whether sales are greater than cost
profitable = sales_data > cost_data

print(profitable)

[[ True  True  True  True  True  True]
 [ True  True  True  True  True  True]
 [ True  True  True  True  True  True]
 [ True  True  True  True  True  True]
 [ True  True  True  True  True  True]]


Question 116: Clip Profit Values
For reporting purposes, management wants profit values limited to:

Minimum: ₹75,000
Maximum: ₹2,50,000
Use np.clip() to create a reporting profit array.

In [255]:
# Calculate profit
profit_data = sales_data - cost_data

# Limit profit between ₹75,000 and ₹2,50,000
reporting_profit = np.clip(
    profit_data,
    75000,
    250000
)

print(reporting_profit)

[[210000 105000  90000  75000  75000  75000]
 [190000 110000  85000  85000  75000  75000]
 [220000  95000  95000  75000  75000  75000]
 [250000 120000 110000  95000  85000  85000]
 [160000  95000  75000  75000  75000  75000]]


Question 117: Normalize Sales Data
Normalize all sales values using min-max normalization:

Normalized Sales =
(Sales - Minimum Sales) / (Maximum Sales - Minimum Sales)

In [256]:
normilized_sales=(sales_data-np.min(sales_data))/(np.max(sales_data)-np.min(sales_data))
print(normilized_sales)

[[0.77142857 0.28       0.15428571 0.11428571 0.01714286 0.05714286]
 [0.69142857 0.32571429 0.13714286 0.15428571 0.04       0.07428571]
 [0.85142857 0.24571429 0.18857143 0.09714286 0.01142857 0.04571429]
 [1.         0.38285714 0.22857143 0.19428571 0.08571429 0.13142857]
 [0.58857143 0.26285714 0.12       0.05714286 0.         0.03428571]]


Question 118: Standardize Sales Data
Standardize sales using:

Standardized Sales =
(Sales - Mean Sales) / Standard Deviation

In [257]:
mean_sales = np.mean(sales_data)
std_sales = np.std(sales_data)
# Standardize sales
standardized_sales = (sales_data - mean_sales) / std_sales

print("Mean:", mean_sales)
print("Standard Deviation:", std_sales)
print(np.round(standardized_sales, 4))

Mean: 389166.6666666667
Standard Deviation: 230322.53954448793
[[ 2.0008  0.1339 -0.3437 -0.4957 -0.8647 -0.7128]
 [ 1.6969  0.3075 -0.4088 -0.3437 -0.7779 -0.6476]
 [ 2.3047  0.0036 -0.2135 -0.5608 -0.8864 -0.7562]
 [ 2.8692  0.5246 -0.0615 -0.1918 -0.6042 -0.4306]
 [ 1.3061  0.0687 -0.474  -0.7128 -0.9299 -0.7996]]


Question 119: Round Values
Convert profit margin values into:

Two decimal places
Nearest whole number
Floor values
Ceiling values

In [258]:
profit_data = sales_data - cost_data

profit_margin = (profit_data / sales_data) * 100
# 1. Two decimal places
two_decimal = np.round(profit_margin, 2)

# 2. Nearest whole number
nearest_whole = np.round(profit_margin)

# 3. Floor values
floor_values = np.floor(profit_margin)

# 4. Ceiling values
ceiling_values = np.ceil(profit_margin)

print("Two decimal places:")
print(two_decimal)

print("\nNearest whole number:")
print(nearest_whole)

print("\nFloor values:")
print(floor_values)

print("\nCeiling values:")
print(ceiling_values)

Two decimal places:
[[24.71 25.   29.03 25.45 34.21 28.89]
 [24.36 23.91 28.81 27.42 33.33 29.17]
 [23.91 24.36 27.94 25.   35.14 27.91]
 [24.76 23.53 29.33 27.54 34.   29.31]
 [23.19 23.46 26.79 24.44 34.29 29.27]]

Nearest whole number:
[[25. 25. 29. 25. 34. 29.]
 [24. 24. 29. 27. 33. 29.]
 [24. 24. 28. 25. 35. 28.]
 [25. 24. 29. 28. 34. 29.]
 [23. 23. 27. 24. 34. 29.]]

Floor values:
[[24. 25. 29. 25. 34. 28.]
 [24. 23. 28. 27. 33. 29.]
 [23. 24. 27. 25. 35. 27.]
 [24. 23. 29. 27. 34. 29.]
 [23. 23. 26. 24. 34. 29.]]

Ceiling values:
[[25. 25. 30. 26. 35. 29.]
 [25. 24. 29. 28. 34. 30.]
 [24. 25. 28. 25. 36. 28.]
 [25. 24. 30. 28. 34. 30.]
 [24. 24. 27. 25. 35. 30.]]


Question 120: Save and Load Data
Save the following arrays as NumPy binary files:

sales_data.npy
cost_data.npy
profit_data.npy
Load them back and verify that the loaded arrays are equal to the original arrays.

In [259]:
# Calculate profit
profit_data = sales_data - cost_data

# Save arrays
np.save("sales_data.npy", sales_data)
np.save("cost_data.npy", cost_data)
np.save("profit_data.npy", profit_data)

In [260]:
import numpy as np

# Profit
profit_data = sales_data - cost_data

# Store-wise calculations
store_sales = np.sum(sales_data, axis=1)
store_cost = np.sum(cost_data, axis=1)
store_profit = np.sum(profit_data, axis=1)
store_margin = (store_profit / store_sales) * 100

# Category-wise calculations
category_sales = np.sum(sales_data, axis=0)
category_cost = np.sum(cost_data, axis=0)
category_profit = np.sum(profit_data, axis=0)
category_margin = (category_profit / category_sales) * 100

# COMPANY SUMMARY

total_sales = np.sum(sales_data)
total_cost = np.sum(cost_data)
total_profit = np.sum(profit_data)
overall_margin = (total_profit / total_sales) * 100

print("## COMPANY SUMMARY")
print("Total Sales:", total_sales)
print("Total Cost:", total_cost)
print("Total Profit:", total_profit)
print("Overall Profit Margin:", round(overall_margin, 2), "%")


# BEST-PERFORMING STORE

best_store_index = np.argmax(store_profit)

print("\n## BEST-PERFORMING STORE")
print("Store:", stores[best_store_index])
print("Sales:", store_sales[best_store_index])
print("Cost:", store_cost[best_store_index])
print("Profit:", store_profit[best_store_index])
print("Profit Margin:", round(store_margin[best_store_index], 2), "%")


# MOST PROFITABLE CATEGORY

best_category_index = np.argmax(category_profit)

print("\n## MOST PROFITABLE CATEGORY")
print("Category:", categories[best_category_index])
print("Sales:", category_sales[best_category_index])
print("Cost:", category_cost[best_category_index])
print("Profit:", category_profit[best_category_index])
print("Profit Margin:", round(category_margin[best_category_index], 2), "%")


# EXPANSION RECOMMENDATIONS

eligible = (
    (store_sales > 2500000) &
    (store_profit > 700000) &
    (store_margin > 25)
)

print("\n## EXPANSION RECOMMENDATIONS")
print("Eligible Stores:")

for store in stores[eligible]:
    print(store)


# COST OPTIMIZATION

profit_margin_matrix = (profit_data / sales_data) * 100

cost_condition = (
    (cost_data > 250000) &
    (profit_margin_matrix < 25)
)

rows, cols = np.where(cost_condition)

print("\n## COST OPTIMIZATION")

for r, c in zip(rows, cols):
    print("Store:", stores[r])
    print("Category:", categories[c])
    print("Cost:", cost_data[r, c])
    print("Profit Margin:", round(profit_margin_matrix[r, c], 2), "%")
    print()


# INVENTORY REORDER

closing_stock = opening_stock - units_sold

reorder_condition = closing_stock < 25

rows, cols = np.where(reorder_condition)

print("\n## INVENTORY REORDER")

for r, c in zip(rows, cols):

    reorder_quantity = 100 - closing_stock[r, c]

    print("Store:", stores[r])
    print("Category:", categories[c])
    print("Closing Stock:", closing_stock[r, c])
    print("Reorder Quantity:", reorder_quantity)
    print()

## COMPANY SUMMARY
Total Sales: 11675000
Total Cost: 8600000
Total Profit: 3075000
Overall Profit Margin: 26.34 %

## BEST-PERFORMING STORE
Store: Mumbai
Sales: 2820000
Cost: 2065000
Profit: 755000
Profit Margin: 26.77 %

## MOST PROFITABLE CATEGORY
Category: Electronics
Sales: 4290000
Cost: 3250000
Profit: 1040000
Profit Margin: 24.24 %

## EXPANSION RECOMMENDATIONS
Eligible Stores:
Mumbai

## COST OPTIMIZATION
Store: Bengaluru
Category: Electronics
Cost: 640000
Profit Margin: 24.71 %

Store: Hyderabad
Category: Electronics
Cost: 590000
Profit Margin: 24.36 %

Store: Hyderabad
Category: Groceries
Cost: 350000
Profit Margin: 23.91 %

Store: Chennai
Category: Electronics
Cost: 700000
Profit Margin: 23.91 %

Store: Chennai
Category: Groceries
Cost: 295000
Profit Margin: 24.36 %

Store: Mumbai
Category: Electronics
Cost: 790000
Profit Margin: 24.76 %

Store: Mumbai
Category: Groceries
Cost: 390000
Profit Margin: 23.53 %

Store: Pune
Category: Electronics
Cost: 530000
Profit Margin: 23.19 

In [261]:


import pandas as pd

df = pd.DataFrame(
    index=stores,
    data=profit_data,
    columns=categories)
print(df)

           Electronics  Groceries  Clothing  Furniture  Beauty  Sports
Bengaluru       210000     105000     90000      70000   65000   65000
Hyderabad       190000     110000     85000      85000   70000   70000
Chennai         220000      95000     95000      65000   65000   60000
Mumbai          260000     120000    110000      95000   85000   85000
Pune            160000      95000     75000      55000   60000   60000


In [262]:
import pandas as pd

df = pd.DataFrame(
    data=cost_data,
    index=stores,
    columns=categories
)

print(df)

           Electronics  Groceries  Clothing  Furniture  Beauty  Sports
Bengaluru       640000     315000    220000     205000  125000  160000
Hyderabad       590000     350000    210000     225000  140000  170000
Chennai         700000     295000    245000     195000  120000  155000
Mumbai          790000     390000    265000     250000  165000  205000
Pune            530000     310000    205000     170000  115000  145000


In [263]:
sales_data

array([[ 850000,  420000,  310000,  275000,  190000,  225000],
       [ 780000,  460000,  295000,  310000,  210000,  240000],
       [ 920000,  390000,  340000,  260000,  185000,  215000],
       [1050000,  510000,  375000,  345000,  250000,  290000],
       [ 690000,  405000,  280000,  225000,  175000,  205000]])

In [264]:
stores

array(['Bengaluru', 'Hyderabad', 'Chennai', 'Mumbai', 'Pune'], dtype='<U9')